const lang = {
  'English':'en',
  'Chinese':'chi',
  'Hindi':'hin',
  'Spanish':'spa',
  'Arabic':'ara',
  'Bangla':'ben',
  'French':'fre',
  'Russian':'rus',
  'Portuguese':'por',
  'Urdu':'urd',
  'Indonesian':'ind',
  'German':'ger',
  'Japanese':'jpn',
  'Marathi':'mar',
  'Telugu':'tel',
  'Turkish':'tur',
  'Tamil':'tam',
  'Hausa':'hau',
  'korean':'kor',
  'Vietnamese':'vie',
  'international signlanguage':'sgn',
  'holland signlanguage':'sgn',
  'germany signlanguage':'sgn',
  'russia signlanguage':'sgn',
  'malaysia signlanguage':'sgn',
  'mexican signlanguage':'sgn',
  'brazil signlanguage':'sgn',
  'signlanguage':'sgn',
  'spain signlanguage':'sgn',
  'england signlanguage':'sgn',
  'austrai signlanguage':'sgn',
  'italy signlanguage':'sgn',
  'india and pakistan signlanguage':'sgn',
  'japan signlanguage':'sgn',
  'china signlanguage':'sgn',
  'turkey signlanguage':'sgn',
  'poland signlanguage'    :'sgn',
  'france signlanguage'    :'sgn',
  'korea signlanguage'     :'sgn',
  'australia signlanguage' :'sgn',
}

export default lang;

