const lang = [
  'English',
  'Chinese',
  'Hindi',
  'Spanish',
  'Arabic',
  'Bangla',
  'French',
  'Russian',
  'Portuguese',
  'Urdu',
  'Indonesian',
  'German',
  'Japanese',
  'Marathi',
  'Telugu',
  'Turkish',
  'Tamil',
  'Hausa',
  'korean',
  'Vietnamese',
  'international signlanguage',
  'holland signlanguage',
  'germany signlanguage',
  'russia signlanguage',
  'malaysia signlanguage',
  'mexican signlanguage',
  'brazil signlanguage',
  'signlanguage',
  'spain signlanguage',
  'england signlanguage',
  'austrai signlanguage',
  'italy signlanguage',
  'india and pakistan signlanguage',
  'japan signlanguage',
  'china signlanguage',
  'turkey signlanguage',
  'poland signlanguage',
  'france signlanguage',
  'korea signlanguage',
  'australia signlanguage',
]

export default lang;

