const lang = {
  English:'en',
  Chinese:'chi',
  Hindi:'hin',
  Spanish:'spa',
  Arabic:'ara',
  Bangla:'ben',
  French:'fre',
  Russian:'rus',
  Portuguese:'por',
  Urdu:'urd',
  Indonesian:'ind',
  German:'ger',
  Japanese:'jpn',
  Marathi:'mar',
  Telugu:'tel',
  Turkish:'tur',
  Tamil:'tam',
  Hausa:'hau',
  korean:'kor',
  Vietnamese:'vie',
  internationalSignlanguage:'intsgn',
  hollandSignlanguage:'holsgn',
  germanySignlanguage:'gersgn',
  russiaSignlanguage:'russgn',
  malaysiaSignlanguage:'malsgn',
  mexicanSignlanguage:'mexsgn',
  brazilSignlanguage:'brasgn',
  signlanguage:'sgn',
  spainSignlanguage:'spnsgn',
  englandSignlanguage:'uksgn',
  austraiSignlanguage:'aussgn',
  italySignlanguage:'itasgn',
  indiaAndPakistanSignlanguage:'indsgn',
  japanSignlanguage:'jpnsgn',
  chinaSignlanguage:'cnsgn',
  turkeySignlanguage:'tksgn',
  polandSignlanguage:'polsgn',
  franceSignlanguage:'frcsgn',
  koreaSignlanguage:'kosgn',
  australiaSignlanguage:'aussgn',
}

export default lang;

