const lang = {
  'English':'en',
  'Chinese':'chi',
  'Hindi':'hin',
  'Spanish':'spa',
  'Arabic':'ara',
  'Bangla':'ben',
  'French':'fre',
  'Russian':'rus',
  'Portuguese':'por',
  'Urdu':'urd',
  'Indonesian':'ind',
  'German':'ger',
  'Japanese':'jpn',
  'Marathi':'mar',
  'Telugu':'tel',
  'Turkish':'tur',
  'Tamil':'tam',
  'Hausa':'hau',
  'korean':'kor',
  'Vietnamese':'vie',
  'international signlanguage':'intsgn',
  'holland signlanguage':'holsgn',
  'germany signlanguage':'gersgn',
  'russia signlanguage':'russgn',
  'malaysia signlanguage':'malsgn',
  'mexican signlanguage':'mexsgn',
  'brazil signlanguage':'brasgn',
  'signlanguage':'sgn',
  'spain signlanguage':'spnsgn',
  'england signlanguage':'uksgn',
  'austrai signlanguage':'aussgn',
  'italy signlanguage':'itasgn',
  'india and pakistan signlanguage':'indsgn',
  'japan signlanguage':'jpnsgn',
  'china signlanguage':'cnsgn',
  'turkey signlanguage':'tksgn',
  'poland signlanguage'    :'polsgn',
  'france signlanguage'    :'frcsgn',
  'korea signlanguage'     :'kosgn',
  'australia signlanguage' :'aussgn',
}

export default lang;

